### ISSUE TITLE
[Feature request] Different leave message if player leaves via transferserver

### ISSUE THREAD

**Issue by Weissnix4711** [JaxkDev/DiscordBot#10]
I personally use this plugin for my lobby. Having the ability to see where players transfer to would be very helpful, and I believe I'm not the only one who would use this feature.

Would also be cool if you could also specify a different message for any specific address and port.

Eg. If the player is transferred to `my.domain.com:19135` the bot will say `{USERNAME} transferred to Factions` but if they transfer to `my.domain.com:19133` it says `{USERNAME} transferred to SMP`. Any other transfer, and it will say the normal leave server message.

All editable in the config file, of course.

**Comment by JaxkDev** [comment]
There’s only so much I plan to add in the config for events, everything else will be possible through plugins / events after I finish up this rewrite plugins can get member,channel,server,role information on demand and they can listen to discordbots events for things like members joining, leaving, chatting in discord.
This means plugins can add their own commands, responses and messages whenever they want in this case when a player transfers players.
But I may consider a default transfer event.

**Comment by Weissnix4711** [comment]
Alright, thank you very much.

**Comment by JaxkDev** [comment]
Message when someone transfers is added, but if they transfer it will also show the leave/disconnect message.

**Comment by JaxkDev** [comment]
Added via 101980e
