### ISSUE TITLE
idk what this is

### ISSUE THREAD

**Issue by strich3** [JaxkDev/DiscordBot#11]
Warning: require_once(/home/SkyBlock/plugins/DiscordBot-master/DiscordBot/vendor/autoload.php): failed to open stream: No such file or directory in /home/SkyBlock/plugins/DiscordBot-master/src/JaxkDev/DiscordBot/Communication/BotThread.php on line 50

Fatal error: require_once(): Failed opening required '/home/SkyBlock/plugins/DiscordBot-master/DiscordBot/vendor/autoload.php' (include_path='.:') in /home/SkyBlock/plugins/DiscordBot-master/src/JaxkDev/DiscordBot/Communication/BotThread.php on line 50

**Comment by JaxkDev** [comment]
Pretty simple don’t run source of you don’t know how, stable releases can be found here https://github.com/JaxkDev/DiscordBot/releases/latest
