### ISSUE TITLE
[bug] stdClass::$url error

### ISSUE THREAD

**Issue by GameParrot** [JaxkDev/DiscordBot#119]
`[2023-12-07T20:34:01.487535+00:00] InternalThread.CRITICAL: ErrorException: "Undefined property: stdClass::$url" (EXCEPTION) in "phar:///home/gameparrot/pocketmine/ng/polr server/plugins/DiscordBot.phar/src/InternalBot/ModelConverter.php" at line 587 [] []` in log, bot unloaded

**Comment by JaxkDev** [comment]
Sorry already noted its poor documentation, will add checks for this case.

https://github.com/DiscordBot-PMMP/DiscordBot/blob/ceab5443197d84c05a450047cbca22cc029e895d/src/InternalBot/ModelConverter.php#L587
