### ISSUE TITLE
Next error please help :(

### ISSUE THREAD

**Issue by strich3** [JaxkDev/DiscordBot#12]
Fatal error: Uncaught BadMethodCallException: unable to create temporary file in /home/SkyBlock/plugins/DiscordBot-1.0.0/BUILD.php:114
Stack trace:
#0 /home/SkyBlock/plugins/DiscordBot-1.0.0/BUILD.php(114): Phar->compressFiles(4096)
#1 /home/SkyBlock/plugins/DiscordBot-1.0.0/BUILD.php(37): buildPhar('/home/SkyBlock/...', '/home/SkyBlock/...', Array, Array, Array, '<?php __HALT_CO...')
#2 {main}
  thrown in /home/SkyBlock/plugins/DiscordBot-1.0.0/BUILD.php on line 114

**Comment by strich3** [comment]
08:02:24 Server|ERROR > Could not load '/home/SkyBlock/plugins/DiscordBot_v1_0_0.phar' in folder '/home/SkyBlock/plugins/': in phar "/home/SkyBlock/plugins/DiscordBot_v1_0_0.phar", manifest claims to have zero entries.  Phars must have at least 1 entry
08:02:24 Server|CRITICAL > UnexpectedValueException: "in phar "/home/SkyBlock/plugins/DiscordBot_v1_0_0.phar", manifest claims to have zero entries. Phars must have at least 1 entry" (EXCEPTION) in "src/pocketmine/plugin/PharPluginLoader" at line 58
08:02:24 Server|CRITICAL > #0 src/pocketmine/plugin/PharPluginLoader(58): Phar->__construct(string[45] /home/SkyBlock/plugins/DiscordBot_v1_0_0.phar)
08:02:24 Server|CRITICAL > #1 src/pocketmine/plugin/PluginManager(238): pocketmine\plugin\PharPluginLoader->getPluginDescription(string[45] /home/SkyBlock/plugins/DiscordBot_v1_0_0.phar)
08:02:24 Server|CRITICAL > #2 src/pocketmine/Server(1608): pocketmine\plugin\PluginManager->loadPlugins(string[23] /home/SkyBlock/plugins/)
08:02:24 Server|CRITICAL > #3 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[15] /home/SkyBlock/, string[23] /home/SkyBlock/plugins/)
08:02:24 Server|CRITICAL > #4 src/pocketmine/PocketMine(304): pocketmine\server()
08:02:24 Server|CRITICAL > #5 (11): require(string[62] phar:///home/SkyBlock/altay.phar/src/pocketmine/PocketMine.php)

**Comment by JaxkDev** [comment]
https://github.com/JaxkDev/DiscordBot/issues/11#issuecomment-764553021 & No support for altay or any other spoons/forks of pmmp.
