### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Project-Econome** [JaxkDev/DiscordBot#121]
chatbridge join and leave server feature not responding and sending an error

**Comment by JaxkDev** [comment]
Need full log/error and versions please.

**Comment by Project-Econome** [comment]
will send soon

**Comment by Project-Econome** [comment]
![image](https://github.com/DiscordBot-PMMP/ChatBridge/assets/108093514/e8a4d060-2139-4167-86dc-0764af201cfb)

slight issue the log file is not opening

**Comment by Project-Econome** [comment]
idk if my computers slow or what i will wait

**Comment by JaxkDev** [comment]
Duplicate #116

**Comment by JaxkDev** [comment]
![Snimek_obrazovky_2024-01-01_192535](https://github.com/DiscordBot-PMMP/DiscordBot/assets/25908768/5f26ef99-69a3-4703-8c65-c497de93dcff)
