### ISSUE TITLE
Bot crashes when automod violation occurs and is logged to a channel

### ISSUE THREAD

**Issue by GameParrot** [JaxkDev/DiscordBot#124]
When an automod violation is logged to a channel, the bot crashes. I have it set to timeout the member on violation and send a report. Without the send report it did not crash. There was no backtrace, just a silent crash.

**Comment by Project-Econome** [comment]
are you using the bot to do automod actions? through mc or discord?
also the report is it to discord themselves as this isnt really possible from what i remember

**Comment by JaxkDev** [comment]
I need more info if it’s specifically the send report crashing it.

what does send report do?
what exactly does it contain?
Can I reproduce it?

**Comment by GameParrot** [comment]
> I need more info if it’s specifically the send report crashing it.
> 
> what does send report do? what exactly does it contain? Can I reproduce it?

To reproduce it, enable automod in discord server settings in a server that the bot is in. Enable send alert and set it to a channel that the bot has access to. Then, log into an alt discord account and trigger the automod. The bot will crash as soon as the automod is triggered.

**Comment by Project-Econome** [comment]
> > I need more info if it’s specifically the send report crashing it.
> > what does send report do? what exactly does it contain? Can I reproduce it?
> 
> To reproduce it, enable automod in discord server settings in a server that the bot is in. Enable send alert and set it to a channel that the bot has access to. Then, log into an alt discord account and trigger the automod. The bot will crash as soon as the automod is triggered.

It seems to not do it for me I don't know what's wrong on your end

**Comment by JaxkDev** [comment]
I have a feeling it would the send alert thats triggering a conversion anomaly.
I shall try to reproduce and fix the issue.

**Comment by JaxkDev** [comment]
This is not an issue with DiscordBot but the underlying library DiscordPHP not having the listed embed type (`auto_moderation_message`) as an allowed type so the library crashes when we try to access the embed.

**Comment by JaxkDev** [comment]
All automod messages are ignored by bot for now.
