### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by cooleoooo66** [JaxkDev/DiscordBot#14]
it tells me the Preferences file is messed up or corroded and I don't know how to fix it. (my webhook for discord is valid)

**Comment by JaxkDev** [comment]
If it’s messed up it’s messed up, I can’t tell you much more then that because that’s all you’ve told me.
And there’s no webhooks...

**Comment by cooleoooo66** [comment]
how do I connect it then

**Comment by JaxkDev** [comment]
https://github.com/JaxkDev/DiscordBot/wiki/Creating-your-discord-bot

**Comment by cooleoooo66** [comment]
ok thank you I  was doing it wrong

**Comment by JaxkDev** [comment]
Assumed resolved.
