### ISSUE TITLE
setup and join error

### ISSUE THREAD

**Issue by efor89** [JaxkDev/DiscordBot#18]
hi i have an error if i join

Server|CRITICAL > ErrorException: "Undefined offset: 1" (EXCEPTION) in "plugins/DiscordBot_v1_0_0.phar/src/JaxkDev/DiscordBot/Plugin/Handlers/PocketMineEventHandler" at line 46

i setup the bot in discord dev then i save the token in config and the channel id in events.

with https://botghost.com/dashboard/  i make the bot online

can you help me plz

**Comment by JaxkDev** [comment]
Looks like you didn’t put the ID’s correctly in events.yml
In DiscordBot v1.0.0 it’s “serverID.channelID”

**Comment by JaxkDev** [comment]
Read the HELP_ENG.txt pretty sure I shipped that in v1

**Comment by efor89** [comment]
thx no it work i only use channelid
