### ISSUE TITLE
connection break after 1-2days

### ISSUE THREAD

**Issue by efor89** [JaxkDev/DiscordBot#20]
hi 
i have the problem that the bot lost the connection after 1-2days, no error.
after a server restart it works again.

**Comment by JaxkDev** [comment]
need the log for the day it stopped working, found in plugin_data/DiscordBot/logs

**Comment by efor89** [comment]
[DiscordBot-2021-02-23.log](https://github.com/JaxkDev/DiscordBot/files/6027707/DiscordBot-2021-02-23.log)

**Comment by efor89** [comment]
i have the bot on 5 server for cross chat with dc

**Comment by efor89** [comment]
[DiscordBot-2021-02-22.log](https://github.com/JaxkDev/DiscordBot/files/6027721/DiscordBot-2021-02-22.log)

**Comment by JaxkDev** [comment]
That log shows everything in tact with discord, it does close at the end and doesn’t appear to restart I assume the plugin disabled for another reason.
`[2021-02-22T12:43:23.438093+00:00] DiscordPHP.INFO: discord closed [] []`

**Comment by JaxkDev** [comment]
Might want to check the server.log at around that time for any problems.

**Comment by efor89** [comment]
2021-02-22 12:43:23 BotThread|EMERGENCY > Plugin has not responded for 2 seconds, shutting self down.

**Comment by JaxkDev** [comment]
Pretty small window was given in 1.0.0 so if you did something like a sync world edit that took longer then 2s it would cause that.
Or your server was experiencing high loads / performance issues.
Currently it doesn’t attempt to reconnect it simply bails.

**Comment by efor89** [comment]
mhhh then i think it was a server lag

**Comment by efor89** [comment]
can you fix it that the bot reconect after a server lag? plz

**Comment by efor89** [comment]
or that more time is give to the bot like 5-10 sec?

**Comment by JaxkDev** [comment]
The whole issue is the bot doesn’t know what’s happened to the plugin it’s not responding so you can’t rely on it if it’s not responding.
In v2.0.0 it’s 10s allowance.
