### ISSUE TITLE
Error loading the plugin

### ISSUE THREAD

**Issue by ZEENKEY** [JaxkDev/DiscordBot#24]
Server Log
```
[06:28:44] [Server thread/INFO]: Enabling DiscordBot v2.0.0
[06:28:44] [Server thread/INFO]: Enabling LightningDeath v1.2.4
[06:28:44] [Server thread/INFO]: Enabling AddNetherite-HiroTeam v2.0.0

Warning: require_once(phar:///home/container/plugins/DiscordBot.phar/vendor/autoload.php): failed to open stream: phar error: "vendor/autoload.php" is not a file in phar "/home/container/plugins/DiscordBot.phar" in phar:///home/container/plugins/DiscordBot.phar/src/JaxkDev/DiscordBot/Communication/BotThread.php on line 54

Fatal error: require_once(): Failed opening required 'phar:///home/container/plugins/DiscordBot.phar/vendor/autoload.php' (include_path='.:') in phar:///home/container/plugins/DiscordBot.phar/src/JaxkDev/DiscordBot/Communication/BotThread.php on line 54
```

**Comment by JaxkDev** [comment]
Use a release.

**Comment by ZEENKEY** [comment]
> Use a release.
> 
> Where did you get that DiscordBot.phar ?

I cloned this repo and compile in phar.scer.io
DevTools don't load the plugin and release don't works.

**Comment by JaxkDev** [comment]
Yeah no you can’t build like that, releases do work but a issue with pmmp php bins means a certain file is missing on Linux/mac

**Comment by ZEENKEY** [comment]
[DiscordBot-2021-03-06.log](https://github.com/JaxkDev/DiscordBot/files/6096181/DiscordBot-2021-03-06.log)
Release 1

**Comment by ZEENKEY** [comment]
> Yeah no you can’t build like that, releases do work but a issue with pmmp php bins means a certain file is missing on Linux/mac

Well, hosting problem? I'll report it.

**Comment by JaxkDev** [comment]
Not a hosting problem, they probably just used php binaries from pmmp which has a active issue regarding the cacert not being there in Linux & Mac so the plugin cant connect to discord.
