### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by xDanub** [JaxkDev/DiscordBot#25]
BotThread thread/CRITICAL Client failed to login/connect within 30 seconds, See log file for details. 

I saw that you closed the other issue regarding this (#22) so I am just wondering if fixed or plugin is not ready yet. Sorry if it is and I am just not able to find it...

**Comment by JaxkDev** [comment]
Assuming it’s the same TLS problem, https://github.com/JaxkDev/DiscordBot/issues/22#issuecomment-791892236

**Comment by xDanub** [comment]
Should be. Thanks for the quick response and the great plugin as usual.

**Comment by xDanub** [comment]
Really appreciate your work
