### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ananinys** [JaxkDev/DiscordBot#26]
hello, help me please, I can’t do point 3

Installing dependencies, Removing any dev-dependencies & Optimising Autoloader...
sh: 1: composer: not found
Building plugin...
PHP Fatal error:  Uncaught Error: Call to undefined function yaml_parse_file() in /home/non/plugins/DiscordBot-master/BUILD.php:135
Stack trace:
#0 /home/non/plugins/DiscordBot-master/BUILD.php(29): generatePluginMetadataFromYml()
#1 {main}
  thrown in /home/non/plugins/DiscordBot-master/BUILD.php on line 135
root@v611218:/home/non/plugins/DiscordBot-master#

**Comment by JaxkDev** [comment]
Without composer and ext-yaml there's no way your going to be able to build this.
