### ISSUE TITLE
Better description

### ISSUE THREAD

**Issue by MrNinja008** [JaxkDev/DiscordBot#35]
I cant understand what this plugin do it is a lib or something else? I dont think it is lib since it has token in resources but idk what this plugin do and how do we use this pls we need a better description to understand.

**Comment by JaxkDev** [comment]
`Please note that this plugin offers no standalone features, It is a central API plugin for other plugins to use/depend on.`

**Comment by JaxkDev** [comment]
In simple user friendly words, It is a library plugin and comes with no default features.

**Comment by MrNinja008** [comment]
> In simple user friendly words, It is a library plugin and comes with no default features.

Ok but why it says paste your bot token in config?

**Comment by JaxkDev** [comment]
Because it’s needed for the plugin to work…

**Comment by JaxkDev** [comment]
Somewhat of a better description added... Will need improving in near future.
