### ISSUE TITLE
How to use this.

### ISSUE THREAD

**Issue by godchadigo** [JaxkDev/DiscordBot#37]
![圖片](https://user-images.githubusercontent.com/19208239/131240835-83977a4e-b05a-4e1d-8d26-e2e7560edb85.png)
HI JaxkDev:
I cant send message to my discord channel @/\@

**Comment by JaxkDev** [comment]
ok will always be dumped because that function always returns a promise.

Read API.md

**Comment by godchadigo** [comment]
ok,thank you.
