### ISSUE TITLE
Debug messages always showing

### ISSUE THREAD

**Issue by Xiaoming0313883** [JaxkDev/DiscordBot#41]
After this message came out "[Server thread/DEBUG]: [DiscordBot] Handled data dump (1633150437) (39)" the other plugin's will report their debug message on console, pocketmine.yml debug was set at 1.
But after I disable DiscordBot plugin, it went back normal
![image](https://user-images.githubusercontent.com/85933240/135704141-f67d9677-ce05-429a-8573-7249839fd17d.png)

**Comment by JaxkDev** [comment]
I don’t quite understand the problem

**Comment by Xiaoming0313883** [comment]
Like when I enabled DiscordBot plugin, the debug message will came out, but I switched debug to false. And my pocketmine.yml debug also closed. But when I disabled discordbot plugin, it when back normal.

**Comment by JaxkDev** [comment]
I think I get what your trying to say but it shouldn’t work like that but I won’t fix it on v2.0 because I’ve already completely ditched pocketmine logger (discord thread) in v2.1 (Pocketmine 4)

**Comment by Xiaoming0313883** [comment]
oh rip Pocketmine 3 ;-;

**Comment by JaxkDev** [comment]
Use v2.0.4 should be fixed.

**Comment by Xiaoming0313883** [comment]
Thanks!
