### ISSUE TITLE
Token Security Suggestion

### ISSUE THREAD

**Issue by Dapro718** [JaxkDev/DiscordBot#5]
Many server owners give console access to their hired developers. I’ve seen many cases where these developers either scam, get fired, or try to mess up the server. When this happens, and this plugin is installed, these developers will get access to the bot token. With this token in hand, these developers can do some nasty things.

I’m suggesting that tokens be setup some other way to improve security. For example, it can be setup in game (/token <token>), then saved to the config or another file encoded.

In the end, this is an awesome plugin, good job!

**Comment by JaxkDev** [comment]
It was much worst before release, used to be logged every time it connects in console/file logs...

In terms of developers doing stuff, the most they can do is assign a few nicknames, send some messages with pings by then someone will probably kick the bot hopefully.
(Assuming you used the preset permissions in the wiki ‘201825345’)

For encryption there’s not much point, anything encrypted has to be decrypted and the decryption method would be public so anyone can decrypt it as it’s in the plugin source...

**Comment by Thunder33345** [comment]
Please define clearly? console, as in console access only? or do you mean full system access? via web panel
From this point onwards, ill assume full access, which one of them is file system access

If your threat vector is file system access, stealing the token
there's not much you defend against it
Like jaxk said, if it's encrypted, it has to be decrypted or else the bot cant start

**This is basically worrying about a vase, while someone is basically heisting your TV and everything away, sweeping your house clean**

The only alternative i can think of is:
In memory tokens, where the server only store the token in memory, and any attempt of tampering with plugins, via rebooting, simply wipes the token clean from memory
But downside of this being the bot token will need to be re-entered every time server restarts or starts up

There's a few ways to limit the scope of damage though:
You can do that by not granting excessive permissions to the discord bot, so in an event of a compromise, the damage is limited within few bridged channels only
which the wiki attempts to do, but it's not worded clearly enough, that that's procedure have a impact on security in limiting scope of damage

**Comment by JaxkDev** [comment]
The wiki has been updated for a more clear Security notice but that’s as much as I can do from the plugin side and have no intent of ‘encrypting’ it or storing in memory due to inconvenience and delayed starts etc.

**Comment by Dapro718** [comment]
Looks good! Just thought it was something to bring up as the internet can be “interesting” at times.
