### ISSUE TITLE
Invite Problem

### ISSUE THREAD

**Issue by DuoIncure** [JaxkDev/DiscordBot#52]
I believe this to be an issue with servers that have vanity/custom invite codes, as there is no specified "inviter" or creator of the invite.
I might be wrong, however it is the only conclusion I have, as other Discord servers without such features loaded as expected.

The issue is seen here: https://www.toptal.com/developers/hastebin/luneyibepo.yaml

**Comment by JaxkDev** [comment]
@DuoIncure I can see the problem, in both my code and DiscordPHP.
Just for completeness I will commit a debug build that will output the exact data from discord of the 'no-inviter' invites, if you could run that build and come back here with the output that will be greatly appreciated.

**Comment by JaxkDev** [comment]
[DiscordBot_v2_1_2.phar.zip](https://github.com/DiscordBot-PMMP/DiscordBot/files/7864521/DiscordBot_v2_1_2.phar.zip) - Github doesn't like phars nor does discord apparently.

**Comment by ErikPDev** [comment]
The same issue is happening to me.

**Comment by JaxkDev** [comment]
> [DiscordBot_v2_1_2.phar.zip](https://github.com/DiscordBot-PMMP/DiscordBot/files/7864521/DiscordBot_v2_1_2.phar.zip) - Github doesn't like phars nor does discord apparently.

@ErikPDev run this one and it will dump the data I need to confirm when it happens.

**Comment by ErikPDev** [comment]
> > [DiscordBot_v2_1_2.phar.zip](https://github.com/DiscordBot-PMMP/DiscordBot/files/7864521/DiscordBot_v2_1_2.phar.zip) - Github doesn't like phars nor does discord apparently.
> 
> @ErikPDev run this one and it will dump the data I need to confirm when it happens.

Okay, Just a moment.

**Comment by ErikPDev** [comment]
Odd, the error no longer happens.
I tried using the poggit phar and the one you provided me.

I'll send a message here if it happens again.

**Comment by JaxkDev** [comment]
The debug phar wont crash just dump some data to output (console) and continue to work as normal.

> Odd, the error no longer happens. I tried using the poggit phar and the one you provided me.
> 
> I'll send a message here if it happens again.

ok.

**Comment by ErikPDev** [comment]
> The debug phar wont crash just dump some data to output (console) and continue to work as normal.
> 
> > Odd, the error no longer happens. I tried using the poggit phar and the one you provided me.
> > I'll send a message here if it happens again.
> 
> ok.

I'll try it again and check the logs.

**Comment by ErikPDev** [comment]
[DiscordBot-2022-03-28.log](https://github.com/DiscordBot-PMMP/DiscordBot/files/8361888/DiscordBot-2022-03-28.log)
There's that pesky error.

**Comment by JaxkDev** [comment]
> [DiscordBot-2022-03-28.log](https://github.com/DiscordBot-PMMP/DiscordBot/files/8361888/DiscordBot-2022-03-28.log)
> There's that pesky error.

I already have that log from duo and one other user I just need the output(var_dump) from that plugin to see what discordphp does to handle no inviter.

**Comment by JaxkDev** [comment]
Just leave it.

Issue has been resolved in DiscordPHP 7.x but will leave the workaround in discordbot while we still run on the old gateway (DiscordPHP 6.x)

**Comment by ErikPDev** [comment]
> > [DiscordBot-2022-03-28.log](https://github.com/DiscordBot-PMMP/DiscordBot/files/8361888/DiscordBot-2022-03-28.log)
> > There's that pesky error.
> 
> I already have that log from duo and one other user I just need the output(var_dump) from that plugin to see what discordphp does to handle no inviter.

Using the dev build, I don't see any output(var_dump) from DiscordBot.

**Comment by ErikPDev** [comment]
I'm not sure the workaround is working.
On the latest Poggit release, the `DiscordBot` plugin keeps disabling.
 According to its log, it's because of `ErrorException: "Undefined array key "inviter"" `
Same error.

**Comment by JaxkDev** [comment]
> I'm not sure the workaround is working.
> On the latest Poggit release, the `DiscordBot` plugin keeps disabling.
> According to its log, it's because of `ErrorException: "Undefined array key "inviter"" `
> Same error.

The workaround isnt released or on poggit, that debug phar is the only phar ive built with some sort of workaround
