### ISSUE TITLE
[Bug] Help

### ISSUE THREAD

**Issue by Bubbelwubbel** [JaxkDev/DiscordBot#53]
![image](https://user-images.githubusercontent.com/65186341/150647736-c565ff83-e4be-4928-a640-c0304fe4fe8f.png)

**Comment by Bubbelwubbel** [comment]
How can I fix this?

**Comment by JaxkDev** [comment]
Send the entire log and plugin log.
Shouldn’t be happening with the cacert file manually provided.

**Comment by Bubbelwubbel** [comment]
I was able to fix it myself, it was an error from the bot, I'll wait a little longer next time and don't open an issue directly
