### ISSUE TITLE
When a user leaves a voice channel with someone else.

### ISSUE THREAD

**Issue by edwinyoo44** [JaxkDev/DiscordBot#54]
Version: DiscordBot 2.1.1

```
2022-02-11 [00:08:56.873] [Server thread/CRITICAL]: AssertionError: "Voice Channel for leaving member '472325129330753536.346938303683231744' not found in storage." (EXCEPTION) in "plugins/DiscordBot_2.1.1.phar/src/Plugin/BotCommunicationHandler" at line 154
--- Stack trace ---
  #0 plugins/DiscordBot_2.1.1.phar/src/Plugin/BotCommunicationHandler(105): JaxkDev\DiscordBot\Plugin\BotCommunicationHandler->handleVoiceStateUpdate(object JaxkDev\DiscordBot\Communication\Packets\Discord\VoiceStateUpdate#123380)
  #1 plugins/DiscordBot_2.1.1.phar/src/Plugin/Main(249): JaxkDev\DiscordBot\Plugin\BotCommunicationHandler->handle(object JaxkDev\DiscordBot\Communication\Packets\Discord\VoiceStateUpdate#123380)
  #2 plugins/DiscordBot_2.1.1.phar/src/Plugin/Main(107): JaxkDev\DiscordBot\Plugin\Main->tick(integer 920)
  #3 pmsrc/src/scheduler/ClosureTask(63): JaxkDev\DiscordBot\Plugin\Main->JaxkDev\DiscordBot\Plugin\{closure}()
  #4 pmsrc/src/scheduler/TaskHandler(117): pocketmine\scheduler\ClosureTask->onRun()
  #5 pmsrc/src/scheduler/TaskScheduler(141): pocketmine\scheduler\TaskHandler->run()
  #6 pmsrc/src/plugin/PluginManager(466): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 920)
  #7 pmsrc/src/Server(1768): pocketmine\plugin\PluginManager->tickSchedulers(integer 920)
  #8 pmsrc/src/Server(1657): pocketmine\Server->tick()
  #9 pmsrc/src/Server(1046): pocketmine\Server->tickProcessor()
  #10 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[45] /home/edwinyoo44/MinecraftBEServer/pmmp_test/, string[53] /home/edwinyoo44/MinecraftBEServer/pmmp_test/plugins/)
  #11 pmsrc/src/PocketMine(327): pocketmine\server()
  #12 pmsrc(11): require(string[95] phar:///home/edwinyoo44/MinecraftBEServer/pmmp_test/PocketMine-MP_4.2.0.phar/src)
--- End of exception information ---
```

**Comment by JaxkDev** [comment]
run `debugdiscord` command in console/in-game and attach the file generated.

**Comment by edwinyoo44** [comment]
> run `debugdiscord` command in console/in-game and attach the file generated.

https://drive.google.com/file/d/1yNFh4lLA7BlTvHtBZoprhxvf63Uz7LhG/view?usp=drivesdk

**Comment by edwinyoo44** [comment]
This is the error log only with DiscortBot plugin

https://drive.google.com/file/d/1y_fzqrfwZW5yaiquJWMbhRfEfOHeJH2u/view?usp=drivesdk

**Comment by JaxkDev** [comment]
Thank you, I know roughly what the problem is this data will help debug exactly and produce a reliable fix.
However I have personal matters to attend to this week so I don’t expect it to be ‘fixed’ before next week.

**Comment by edwinyoo44** [comment]
Thanks a lot!

**Comment by JaxkDev** [comment]
I must say your brave running this with JIT, several PHP Bugs have been found by this project before I wouldn’t be surprised if you run into more.

**Comment by edwinyoo44** [comment]
> Thank you, I know roughly what the problem is this data will help debug exactly and produce a reliable fix. However I have personal matters to attend to this week so I don’t expect it to be ‘fixed’ before next week.



Is there any processing?

**Comment by JaxkDev** [comment]
> > Thank you, I know roughly what the problem is this data will help debug exactly and produce a reliable fix. However I have personal matters to attend to this week so I don’t expect it to be ‘fixed’ before next week.
> 
> Is there any processing?

If I remember correctly It wasn’t possible to debug it as I couldn’t reproduce it and your debug data was prior/post error so wouldn’t include certain data like members in channel.

I will look again and see where I got to next week, Im extremely busy this week.

**Comment by JaxkDev** [comment]
I can't reproduce it, are you able to reproduce all the time ?
If so whats the steps by steps to reproduce and whats the environment like ? (how many users are in channel when bot starts, how many are in the channel just before you leave, how many join with you etc)

**Comment by edwinyoo44** [comment]
> I can't reproduce it, are you able to reproduce all the time ? If so whats the steps by steps to reproduce and whats the environment like ? (how many users are in channel when bot starts, how many are in the channel just before you leave, how many join with you etc)

I just tried it again and it all worked and I can't reproduce the issue now

At the time, I started PocketMine Server, then randomly entered a Discord voice channel, and then exited and encountered that problem

**Comment by edwinyoo44** [comment]
@JaxkDev 
I just reproduced the problem
1. User A enters channel A
2. User B enters channel A
3. User B leaves channel A

Below is a video for reference

https://youtu.be/U7SNJUq9tkI

**Comment by JaxkDev** [comment]
I’ve tried something like that as I can see how that sort of bug can occur but couldn’t reproduce, does that happen every time you do that?
And does it happen with JIT disabled?

**Comment by edwinyoo44** [comment]
> I’ve tried something like that as I can see how that sort of bug can occur but couldn’t reproduce, does that happen every time you do that? And does it happen with JIT disabled?

Yes, it happens every time I do this
The same happens after I turn off JIT

Below is PocketMine information

[15:35:07.624] [Server thread/INFO]: Plugins (2): DevTools v1.15.0, DiscordBot v2.1.1
[15:35:18.524] [Server thread/INFO]: This server is running PocketMine-MP
[15:35:18.525] [Server thread/INFO]: Server version: 4.3.1 (git hash: f7dce4af8802ce28a8286e1c8002af19cf986c62)
[15:35:18.525] [Server thread/INFO]: Compatible Minecraft version: 1.18.30 (protocol version: 503)
[15:35:18.525] [Server thread/INFO]: PHP version: 8.0.17
[15:35:18.525] [Server thread/INFO]: PHP JIT: disabled
[15:35:18.525] [Server thread/INFO]: Operating system: linux

**Comment by JaxkDev** [comment]
> > I’ve tried something like that as I can see how that sort of bug can occur but couldn’t reproduce, does that happen every time you do that? And does it happen with JIT disabled?
> 
> Yes, it happens every time I do this The same happens after I turn off JIT
> 
> Below is PocketMine information
> 
> [15:35:07.624] [Server thread/INFO]: Plugins (2): DevTools v1.15.0, DiscordBot v2.1.1 [15:35:18.524] [Server thread/INFO]: This server is running PocketMine-MP [15:35:18.525] [Server thread/INFO]: Server version: 4.3.1 (git hash: f7dce4af8802ce28a8286e1c8002af19cf986c62) [15:35:18.525] [Server thread/INFO]: Compatible Minecraft version: 1.18.30 (protocol version: 503) [15:35:18.525] [Server thread/INFO]: PHP version: 8.0.17 [15:35:18.525] [Server thread/INFO]: PHP JIT: disabled [15:35:18.525] [Server thread/INFO]: Operating system: linux

Ok, thank you I will try to reproduce later today if not I will ask for some debug data at certain points during reproducing steps from you.

**Comment by edwinyoo44** [comment]
> > > I’ve tried something like that as I can see how that sort of bug can occur but couldn’t reproduce, does that happen every time you do that? And does it happen with JIT disabled?
> > 
> > 
> > Yes, it happens every time I do this The same happens after I turn off JIT
> > Below is PocketMine information
> > [15:35:07.624] [Server thread/INFO]: Plugins (2): DevTools v1.15.0, DiscordBot v2.1.1 [15:35:18.524] [Server thread/INFO]: This server is running PocketMine-MP [15:35:18.525] [Server thread/INFO]: Server version: 4.3.1 (git hash: f7dce4af8802ce28a8286e1c8002af19cf986c62) [15:35:18.525] [Server thread/INFO]: Compatible Minecraft version: 1.18.30 (protocol version: 503) [15:35:18.525] [Server thread/INFO]: PHP version: 8.0.17 [15:35:18.525] [Server thread/INFO]: PHP JIT: disabled [15:35:18.525] [Server thread/INFO]: Operating system: linux
> 
> Ok, thank you I will try to reproduce later today if not I will ask for some debug data at certain points during reproducing steps from you.

If you need a timely conversation, you can contact me directly, or through other means

https://fb.me/edwinyoo44

**Comment by JaxkDev** [comment]
Failed to reproduce must be further variables that are playing a part here, my next feeling is permissions on viewing or something.

**Comment by JaxkDev** [comment]
@edwinyoo44 when you're next available please do the following:

1. Start Server the exact same way you did in that video to reproduce the issue.
2. run /debugdiscord in console/ingame
3. Have user A join the voice channel.
4. run /debugdiscord in console/ingame
5. Have user B join the voice channel.
6. run /debugdiscord in console/ingame
7. user B leave.
8. If the error does not occur then skip all further steps
9. Attach ***ALL 3*** of the debug data files from plugin_data/DiscordBot/Debug to this issue.

**Comment by edwinyoo44** [comment]
> @edwinyoo44 when you're next available please do the following:
> 
> 1. Start Server the exact same way you did in that video to reproduce the issue.
> 2. run /debugdiscord in console/ingame
> 3. Have user A join the voice channel.
> 4. run /debugdiscord in console/ingame
> 5. Have user B join the voice channel.
> 6. run /debugdiscord in console/ingame
> 7. user B leave.
> 8. If the error does not occur then skip all further steps
> 9. Attach _**ALL 3**_ of the debug data files from plugin_data/DiscordBot/Debug to this issue.

I just tried it and can't reproduce the problem

**Comment by JaxkDev** [comment]
Again I can't reproduce, if anyone can reproduce this FOLLOW THE STEPS LISTED ABOVE,
