### ISSUE TITLE
How to change default presence.

### ISSUE THREAD

**Issue by OxBrutal** [JaxkDev/DiscordBot#70]
![Screenshot_20220802-071153](https://user-images.githubusercontent.com/61906304/182265444-c227187a-3a48-4f10-90a3-a66368ef411d.jpg)

* How do I change the view?

**Comment by JaxkDev** [comment]
`Api::updateBotPresence()` https://github.com/DiscordBot-PMMP/DiscordBot/blob/68a3d3ea0ddd3bc844b7b26f0e94aff93ca3504b/src/Plugin/Api.php#L425

Example
https://github.com/DiscordBot-PMMP/ChatBridge/blob/d98deed715367028372c4a6ed75797474aa04fec/src/EventListener.php#L73
