### ISSUE TITLE
Weird thing with The Api::addRole

### ISSUE THREAD

**Issue by TheRiddler08** [JaxkDev/DiscordBot#71]
```php
  /**
     * Give the member a role.
     *
     * @param string $member_id
     * @param string $role_id
     * @return PromiseInterface Resolves with no data.
     */
    public function addRole(string $member_id, string $role_id): PromiseInterface{
        [$sid, $uid] = explode(".", $member_id);
        if(!Utils::validDiscordSnowflake($sid) or !Utils::validDiscordSnowflake($uid)){
            return rejectPromise(new ApiRejection("Invalid member ID '$member_id'."));
        }
        if(!Utils::validDiscordSnowflake($role_id)){
            return rejectPromise(new ApiRejection("Invalid role ID '$role_id'."));
        }
        $pk = new RequestAddRole($sid, $uid, $role_id);
        $this->plugin->writeOutboundData($pk);
        return ApiResolver::create($pk->getUID());
    }
    ```
    
    Thats the code for the api above if you look the member_idis the Author id Like Server_id.member_id in Message::getAuthorId() Now why is this lol i spent a good 45min wondering what array key was undefined could this either be removed or chaged to Serverid and then message id?

**Comment by JaxkDev** [comment]
Message ID is completely useless here so not sure what the problem is exactly.

the MEMBER ID is serverID.userID
the USER ID is just userID
And this won’t change

**Comment by TheRiddler08** [comment]
Ahh ok i was kinda confused but yh its fine
and i ment member id not message id lol sorry

**Comment by JaxkDev** [comment]
User and Member are two different things.
A user is a discord user in general while a member is a user inside a specific guild/server
