### ISSUE TITLE
SUggestion Api::hasRole

### ISSUE THREAD

**Issue by TheRiddler08** [JaxkDev/DiscordBot#72]
Can there be A added In The api ot check if a user has the role? Like hasRole($member_id, $role_id) 
And then can there be a getRoles($member_id) it would return all roles the user has in a array?

**Comment by JaxkDev** [comment]
The member would have all that information.

see `Storage::getMember`

**Comment by JaxkDev** [comment]
https://github.com/DiscordBot-PMMP/DiscordBot/blob/68a3d3ea0ddd3bc844b7b26f0e94aff93ca3504b/src/Plugin/Storage.php#L249

https://github.com/DiscordBot-PMMP/DiscordBot/blob/68a3d3ea0ddd3bc844b7b26f0e94aff93ca3504b/src/Models/Member.php#L140
