### ISSUE TITLE
Silent Crash

### ISSUE THREAD

**Issue by OxBrutal** [JaxkDev/DiscordBot#74]
* Why now discord bot plugin often disable itself?
![Screenshot_20220813-161416](https://user-images.githubusercontent.com/61906304/184477347-76cc7692-f73d-454c-a938-89ae216f79a4.jpg)

**Comment by JaxkDev** [comment]
Check the logs yourself in plugin_data or send the file generated from /debugdiscord

**Comment by OxBrutal** [comment]
Oke wait

**Comment by OxBrutal** [comment]
Here
* https://pastebin.com/2L5MLi1p

**Comment by OxBrutal** [comment]
> Check the logs yourself in plugin_data or send the file generated from /debugdiscord

Here
* https://pastebin.com/2L5MLi1p

**Comment by JaxkDev** [comment]
https://pastebin.com/rC69QDfv

**Comment by JaxkDev** [comment]
Duplicate of #66
