### ISSUE TITLE
Plugin will not run with xdebug due to performance drops.

### ISSUE THREAD

**Issue by PPEyt** [JaxkDev/DiscordBot#75]
It crashes my Server

**Comment by JaxkDev** [comment]
Yes, PMMP now ships xdebug by default but not enabled I need to change it to check if enabled too.

**Comment by PPEyt** [comment]
It Works now

**Comment by JaxkDev** [comment]
Resolved as of 57218dfccc98e2757356e808db4cede023b273e5 (v2.1.5)
