### ISSUE TITLE
attachments error

### ISSUE THREAD

**Issue by Laith98Dev** [JaxkDev/DiscordBot#78]
New error with attachments
`AssertionError: "Size '0 bytes' is invalid."`

here's the fully log
[DiscordBot-2022-09-24.log](https://github.com/DiscordBot-PMMP/DiscordBot/files/9637575/DiscordBot-2022-09-24.log)

this happened when probot send this photo
![image](https://user-images.githubusercontent.com/49840784/192071858-49419f75-a5c2-4a9b-8235-1713aa30ede9.png)

**Comment by JaxkDev** [comment]
Updated bounds, v2.1.6+ will contain the update
