### ISSUE TITLE
Unknown message type on delete

### ISSUE THREAD

**Issue by fernanACM** [JaxkDev/DiscordBot#79]
Suddenly, he turned off by himself and I got this message. Why is this?
![Screenshot_20221013_124300.png](https://user-images.githubusercontent.com/83558341/195676351-db1c771e-65b7-441e-ba76-9e46435070ba.png)

**Comment by JaxkDev** [comment]
I need more reproducing steps then just the log on this issue, duplicate of #67 

What sort of messages/channels/category etc is being deleted at the time it crashes

**Comment by fernanACM** [comment]
@JaxkDev Do you want me to pass you the registration of the bot?

**Comment by JaxkDev** [comment]
> @JaxkDev Do you want me to pass you the registration of the bot?

No! Never give your bot token to other people, no matter what.

i just need to know whats happening inside the discord server when this occurs, looks like a message being deleted but not a recognised type so could be something new in discord (potentially thread related)

**Comment by fernanACM** [comment]
Well, at a certain moment when I'm inside with some colleagues, the bot stops working, it doesn't interact by discord and by the game. It's a bit strange actually.

**Comment by JaxkDev** [comment]
No ignore minecraft and ignore the discord bot, what happens inside discord when it happens?
It's saying a message or something similar is being deleted I need to whats being deleted as its not a standard message by looks of it.

**Comment by JaxkDev** [comment]
Most likely same issue with the application interactions, assumed fixed for your specific problem as of v2.1.6+
