### ISSUE TITLE
[Help] Channel Not Found

### ISSUE THREAD

**Issue by ItsJohnny30** [JaxkDev/DiscordBot#82]
![image](https://user-images.githubusercontent.com/88237497/210135116-cddb1f04-d3b0-4049-a20f-6db8fec237cf.png)

The Image Of The Bug.

Join The Stage Channel Will Crash Server.

Pls Fix This!!

**Comment by JaxkDev** [comment]
Need the entire log, either run /debugdiscord or attach that days log from plugin_data/DiscordBot/logs
And what channel is that? Is that a DM?

**Comment by ItsJohnny30** [comment]
> 需要整个日志，要么运行 /debugdiscord 要么从 plugin_data/DiscordBot/logs 附加那天日志 那是什么频道？那是DM吗？

Not, that is Stage Channel

**Comment by JaxkDev** [comment]
No further data provided.
