### ISSUE TITLE
Undefined "Author" key 

### ISSUE THREAD

**Issue by Laith98Dev** [JaxkDev/DiscordBot#83]
I don't know why this happen but i just found the plugin disabled with this error 

`ErrorException: "Undefined array key "author"" (EXCEPTION) in "phar:///root/arab/plugins/DiscordBot.phar/vendor/team-reflex/discord-php/src/Discord/Parts/Channel/Message.php" at line 326 [] []`

Using v2.1.6

Fully logs
[DiscordBot-2022-12-31.log](https://github.com/DiscordBot-PMMP/DiscordBot/files/10327731/DiscordBot-2022-12-31.log)

**Comment by JaxkDev** [comment]
Known issue #66 but I think I struggled to reproduce or didn’t get round to looking again

**Comment by JaxkDev** [comment]
Going to close as dupe, but thank you for log.
