### ISSUE TITLE
Unknown message types on delete

### ISSUE THREAD

**Issue by ItsJohnny30** [JaxkDev/DiscordBot#85]
help, bot was offline.  Console display "plugin disabled".  help

Log file:

[DiscordBot-2023-02-05.log](https://github.com/DiscordBot-PMMP/DiscordBot/files/10610909/DiscordBot-2023-02-05.log)

**Comment by JaxkDev** [comment]
Review all new message types.
https://discord.com/developers/docs/resources/channel#message-object-message-types

**Comment by ItsJohnny30** [comment]
how to fix ah?

**Comment by JaxkDev** [comment]
Apologies for delay, fixed in v2.1.8 (via e5b7892)
