### ISSUE TITLE
PM5 Version

### ISSUE THREAD

**Issue by xS91D** [JaxkDev/DiscordBot#87]
Update To PM5 

https://github.com/pmmp/pthreads/releases/tag/5.0.0 

pm5 remove "Volatile" , plugin will not work in pm5 ...

**Comment by JaxkDev** [comment]
That is not PM5, that is pthreads 5.0.

Anyway, PM5 is not released and since I don’t have the time right now to even attempt updating this I won’t have time to update it before the planned PM5 release date.

**Comment by JaxkDev** [comment]
See #88
