### ISSUE TITLE
PHP 8.1+ / PMMP 5.0 Compatibility

### ISSUE THREAD

**Issue by ghost** [JaxkDev/DiscordBot#88]
PMMP4.21.0 requires ^PHP8.1
https://github.com/pmmp/PocketMine-MP/releases/tag/4.21.0
  
Then occour this error.
please fix it.
```
Warning: Uncaught Error: Object of class UnwindExit could not be converted to string in phar:///xxx/plugins/DiscordBot_v2_1_6.phar/vendor/team-reflex/discord-php/src/Discord/Parts/Part.php:28
```

**Comment by JaxkDev** [comment]
Hmmm, I recall specifying just PHP 8.0 so if its running out of box on 8.1 this is indeed an issue.

**Comment by ghost** [comment]
And occur this error.

```
[Server thread/CRITICAL]: Could not load plugin 'DiscordBot': Incompatible version 8.1.19 of PHP extension 'phar' (plugin requires: < 8.1.0)
```

**Comment by JaxkDev** [comment]
That is not a reportable error, I specifically just added that as PHP 8.1 is NOT yet supported and plugin shouldn’t be loaded

**Comment by ghost** [comment]
Ok, I see.
So v2.1.7 doesn't work, but is only released.

**Comment by JaxkDev** [comment]
v2.1.7 does work but it fixes the PHP compatibility in plugin.yml
So essentially 4.0.0(8.0) - 4.20.4(8.0)

**Comment by ghost** [comment]
I see. Thanks man :D

**Comment by JaxkDev** [comment]
Important note to everyone who wonders across this,

This issue will be tied with #87 since updating to DiscordPHP v7 to include more features will require a general rewrite of the model/api structure.

v3.0.0 is now in development, targeting PHP8.1 (potentially 8.2 TBC) and PMMP 5.0
